# Use postgres/example user/password credentials
version: '3.8'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: aiohttp
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: aiohttp
    ports:
      - 5433:5433

